A, B, C = map(float, raw_input().split(" "))
area_triangle = float((1.0/2) * A * C)
area_circle = float(3.14159 * C * C)
area_trap = float((1.0/2) * (A + B) * C)
area_square = float(B * B)
area_rect = float(A * B)
print('TRIANGULO: %.3f' %area_triangle)
print('CIRCULO: %.3f' %area_circle)
print ('TRAPEZIO: %.3f' %area_trap)
print ('QUADRADO: %.3f'%area_square)
print ('RETANGULO: %.3f'%area_rect)